# Generated by Django 2.2.5 on 2021-01-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_table', models.CharField(max_length=30)),
                ('column_category', models.CharField(max_length=30)),
                ('meta_column', models.CharField(max_length=100)),
                ('odk_datatype', models.CharField(max_length=50)),
                ('choice_list', models.CharField(blank=True, max_length=100, null=True)),
                ('odk_question', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=300)),
                ('datatype', models.CharField(max_length=50)),
                ('required', models.BooleanField()),
                ('serial_number', models.IntegerField()),
            ],
        ),
    ]
