# Generated by Django 2.2.5 on 2021-01-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAPI', '0002_auto_20210125_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='householddata',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='householdquestions',
            table='household_questions',
        ),
    ]
