# Generated by Django 2.2.5 on 2021-01-24 18:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAPI', '0003_auto_20210125_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='householddata',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
