# Generated by Django 2.2.5 on 2021-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAPI', '0004_householddata_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householddata',
            name='id',
        ),
        migrations.AlterField(
            model_name='householddata',
            name='key',
            field=models.CharField(default='eeeeee', max_length=200, primary_key=True, serialize=False),
        ),
    ]
