# Generated by Django 2.2.5 on 2021-01-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAPI', '0005_auto_20210125_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldata',
            options={'managed': True},
        ),
    ]
