# Generated by Django 2.2.5 on 2021-01-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataAPI', '0006_auto_20210125_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='parent_key',
            field=models.ForeignKey(default='uuid:c181415b-19ad-43a1-8580-1f58cd56522d', on_delete=django.db.models.deletion.CASCADE, to='dataAPI.HouseholdData'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='sn',
            field=models.CharField(default='eeeeeee', max_length=200, primary_key=True, serialize=False),
        ),
    ]
