# Generated by Django 2.2.5 on 2021-01-11 05:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rangeli',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.BigIntegerField(blank=True, null=True)),
                ('dcode', models.BigIntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('dan', models.CharField(blank=True, max_length=50, null=True)),
                ('das', models.BigIntegerField(blank=True, null=True)),
                ('gapa_napa', models.CharField(blank=True, max_length=50, null=True)),
                ('type_gn', models.CharField(blank=True, max_length=50, null=True)),
                ('gn_code', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('new_ward_n', models.BigIntegerField(blank=True, null=True)),
                ('ddgnww', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('center', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.BigIntegerField(blank=True, null=True)),
                ('ddgn', models.BigIntegerField(blank=True, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ddgn_code', models.BigIntegerField(blank=True, null=True)),
                ('wardnumber', models.BigIntegerField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('studyarea', models.CharField(blank=True, max_length=1, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('total_popu', models.BigIntegerField(blank=True, null=True)),
                ('male_popu', models.BigIntegerField(blank=True, null=True)),
                ('female_pop', models.BigIntegerField(blank=True, null=True)),
                ('vcode', models.BigIntegerField(blank=True, null=True)),
                ('total_abse', models.BigIntegerField(blank=True, null=True)),
                ('male_abse', models.BigIntegerField(blank=True, null=True)),
                ('female_abs', models.BigIntegerField(blank=True, null=True)),
                ('orig_fid', models.BigIntegerField(blank=True, null=True)),
                ('house', models.BigIntegerField(blank=True, null=True)),
                ('household', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'rangeli',
                'managed': False,
            },
        ),
    ]
