# Generated by Django 2.2.5 on 2021-01-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapLayersAPI', '0002_bridge_contour_landuse_municipalservice_places_river_roadpolygon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='river',
            options={'managed': True},
        ),
    ]
