# Generated by Django 2.2.5 on 2021-01-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapLayersAPI', '0003_auto_20210124_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='antecedant',
        ),
        migrations.RemoveField(
            model_name='river',
            name='join_count',
        ),
        migrations.RemoveField(
            model_name='river',
            name='migrate_lo',
        ),
        migrations.RemoveField(
            model_name='river',
            name='migrate_me',
        ),
        migrations.RemoveField(
            model_name='river',
            name='migrate_sh',
        ),
        migrations.RemoveField(
            model_name='river',
            name='migratio_1',
        ),
        migrations.RemoveField(
            model_name='river',
            name='migration',
        ),
        migrations.RemoveField(
            model_name='river',
            name='migration1',
        ),
        migrations.RemoveField(
            model_name='river',
            name='migration_field',
        ),
        migrations.RemoveField(
            model_name='river',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='river',
            name='objectid_1',
        ),
        migrations.RemoveField(
            model_name='river',
            name='shape_le_1',
        ),
        migrations.RemoveField(
            model_name='river',
            name='shape_leng',
        ),
    ]
