# Generated by Django 2.2.5 on 2021-01-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapLayersAPI', '0004_auto_20210124_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'managed': True},
        ),
    ]
