# Generated by Django 2.2.5 on 2021-01-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapLayersAPI', '0005_auto_20210124_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='vil81_1_field',
        ),
        migrations.RemoveField(
            model_name='places',
            name='vil81_1_id',
        ),
    ]
